// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ApplyCert(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Record<string, any>>;

export function CheckRemoteCert(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DebugDB():Promise<Record<string, any>>;

export function DeleteCert(arg1:number):Promise<void>;

export function FetchZones(arg1:string):Promise<Array<Record<string, any>>>;

export function GetCertDetail(arg1:number):Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, any>>;

export function ImportCertFromPEM(arg1:string):Promise<Record<string, any>>;

export function ListCerts():Promise<Array<Record<string, any>>>;

export function LoadAccounts():Promise<Array<Record<string, any>>>;

export function LoadAllData():Promise<Record<string, any>>;

export function LoadZones():Promise<Array<Record<string, any>>>;

export function OpenPath(arg1:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function UpdateAccount(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function VerifyAccount(arg1:string):Promise<boolean>;
