// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3);
}

export function ApplyCert(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ApplyCert'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CheckRemoteCert(arg1, arg2) {
  return window['go']['main']['App']['CheckRemoteCert'](arg1, arg2);
}

export function DebugDB() {
  return window['go']['main']['App']['DebugDB']();
}

export function DeleteCert(arg1) {
  return window['go']['main']['App']['DeleteCert'](arg1);
}

export function FetchZones(arg1) {
  return window['go']['main']['App']['FetchZones'](arg1);
}

export function GetCertDetail(arg1) {
  return window['go']['main']['App']['GetCertDetail'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportCertFromPEM(arg1) {
  return window['go']['main']['App']['ImportCertFromPEM'](arg1);
}

export function ListCerts() {
  return window['go']['main']['App']['ListCerts']();
}

export function LoadAccounts() {
  return window['go']['main']['App']['LoadAccounts']();
}

export function LoadAllData() {
  return window['go']['main']['App']['LoadAllData']();
}

export function LoadZones() {
  return window['go']['main']['App']['LoadZones']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3);
}

export function VerifyAccount(arg1) {
  return window['go']['main']['App']['VerifyAccount'](arg1);
}
